name: joblinc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.6.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  loader_overlay: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    