name: joblinc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  avatars: ^3.0.0
  dio: ^5.8.0+1
  file_picker: ^9.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  readmore: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_stripe: ^11.4.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.6.0
  get_it: ^8.0.3
  http_parser: ^4.1.2
  hyperlink: ^0.0.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  loader_overlay: ^5.0.0
  mailer: ^6.4.1
  open_file: ^3.5.10
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.1
  path_provider: ^2.1.5
  video_player: ^2.9.5
  url_launcher: ^6.3.1
  dropdown_button2: ^2.3.8
  flutter_pdfview: ^1.4.0+1
  photo_view: ^0.15.0
  get_thumbnail_video: ^0.7.3
  webview_flutter: ^4.11.0
  permission_handler: ^12.0.0+1
  mime: ^2.0.0
  pdf_render: ^1.4.12

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.3.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  mocktail: ^1.0.4
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
