// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmFiIJcppIBUZz5eqyS0jxGl7q2NmF2xE',
    appId: '1:1026201483663:web:5cd5a376768f4b1af2f3fa',
    messagingSenderId: '1026201483663',
    projectId: 'joblinc-a7f4e',
    authDomain: 'joblinc-a7f4e.firebaseapp.com',
    storageBucket: 'joblinc-a7f4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgt4mWxwr-QonyqoOghm5OtjAHQ5LWvs',
    appId: '1:1026201483663:android:5e8f8b8635004adff2f3fa',
    messagingSenderId: '1026201483663',
    projectId: 'joblinc-a7f4e',
    storageBucket: 'joblinc-a7f4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHAYk79AGILePqhbxukgZUURII-b24xo',
    appId: '1:1026201483663:ios:864cee0a8bcb8e91f2f3fa',
    messagingSenderId: '1026201483663',
    projectId: 'joblinc-a7f4e',
    storageBucket: 'joblinc-a7f4e.firebasestorage.app',
    androidClientId: '1026201483663-au9jsqfhef997u6h1gtvaq0iklckllel.apps.googleusercontent.com',
    iosClientId: '1026201483663-n90hdlhusnb3chtm482er8ts91k2b5j2.apps.googleusercontent.com',
    iosBundleId: 'com.ahmedmohsen.joblinc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHAYk79AGILePqhbxukgZUURII-b24xo',
    appId: '1:1026201483663:ios:856f1c18e321e201f2f3fa',
    messagingSenderId: '1026201483663',
    projectId: 'joblinc-a7f4e',
    storageBucket: 'joblinc-a7f4e.firebasestorage.app',
    androidClientId: '1026201483663-au9jsqfhef997u6h1gtvaq0iklckllel.apps.googleusercontent.com',
    iosClientId: '1026201483663-tg806hjrqtuiugkcorfhebbpe91lrujf.apps.googleusercontent.com',
    iosBundleId: 'com.example.joblinc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmFiIJcppIBUZz5eqyS0jxGl7q2NmF2xE',
    appId: '1:1026201483663:web:6350fe777e7cb771f2f3fa',
    messagingSenderId: '1026201483663',
    projectId: 'joblinc-a7f4e',
    authDomain: 'joblinc-a7f4e.firebaseapp.com',
    storageBucket: 'joblinc-a7f4e.firebasestorage.app',
  );

}